<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:sequence>
        <xs:simpleType name="TILUMINACION">
            <xs:restriction base="xs:string">
                <xs:enumeration value="Natural" />
                <xs:enumeration value="Artificial" />
            </xs:restriction>
        </xs:simpleType>
        <xs:simpleType name="TZONA">
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1" />
                <xs:maxInclusive value="10" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="TCODIGO">
            <xs:restriction base="xs:string">
                <xs:length value="6" />
                <xs:pattern value="[0-9]{6}" />
            </xs:restriction>
        </xs:simpleType>

        <xs:element name="CATALOGO">
            <xs:complexType>

                <xs:sequence>
                    <xs:element name="PLANTA" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="IDENTIFICADOR">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="IDIOMA" type="xs:string"
                                                    use="required" />
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>

                            </xs:sequence>

                        </xs:complexType>
                    </xs:element>
                </xs:secuence>
                    <xs:element name="DATOS">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="ZONA" type="TZONA" />
                                <xs:element name="ILUMINACION" type="TILUMINACION" minOccurs="0" />
                                <xs:element name="PRECIO" type="xs:decimal" />
                                <xs:element name="CODIGO" type="TCODIGO" />
                            </xs:sequence>
                            <xs:attribute name="GRUPO_BOTANICO" type="GRUPO_BOTANICO" use="required" />
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:schema>