<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT videoClub (pelicula*)>
<!ELEMENT pelicula (titulo, pais, director+, interpretes*, genero+, duracion, año)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>   
<!ELEMENT interpretes (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ATTLIST titulo num.referencia ID #REQUIRED>
<!ATTLIST pais idioma CDATA #IMPLIED>
<!ATTLIST duracion formato (2D|3D) #REQUIRED>